***
# <font color=green size=10>**DS-002 - GERENCIAMENTO DE DADOS PARA ANÁLISE - AULA 01**</font>
***

**1. Pergunta orientadora:** Quais conjuntos de atributos se associam ao elevado número de casos de dengue no Brasil?

**2. Experiência da disciplina:** Obtenção de base de dados no Kaggle sobre Dengue, pré-processamento e análise exploratória de dados.

**3. Base de Dados que utilizaremos:**
[Link-Dados-Dengue-Brasil](https://www.kaggle.com/datasets/jimmyyyyyyy/dengue-in-brazil-2012-2021?select=State_Dengue_Model_Data_w_pop.csv). Apesar deste link, utilize a base que está no Moodle.

## <font color=green size=6>**01. LEMBRETES IMPORTANTES**</font>

In [ ]:
########################
### ALGUNS LEMBRETES ###
########################

# Este arquivo aqui no qual você está é chamado de notebook.

# Este texto aqui é um comentário.
# Ele sempre aparecerá nessa tonalidade de verde.

# O Python sabe identificar um comentário porque colocamos antes do texto o
# símbolo '#'.

# Notebooks são organizados em 2 tipos de "células":
# (1) Texto (ex.: campo acima) e (2) Código (ex. esta aqui).

# Veja um exemplo de código a seguir:

nome = input("Qual é o seu primeiro nome? Resposta: ")
resposta = input("Este é o seu 1º curso de Ciência de Dados? Se sim, escreva s. Para não, n. Resposta: ")
if resposta == 's':
    print(f"Muito prazer, ", nome,
          "! Bom contar contigo nesta disciplina, que é a sua primeira experiência com Ciência de Dados :)")
else:
    print(f"Muito prazer, ", nome, "! Bom contar contigo nesta disciplina :)")

# Para executar o código, acione as teclas "CTRL + ENTER" ou
# use o botão "Run", com o símbolo de 'Play'.

# Note que, após a execução do código, nenhum comentário foi exibido abaixo.

# Atenção: não se esqueça de que códigos devem ser organizados como
# sequências de comandos.

Qual é o seu primeiro nome? Resposta: Kelvin
Este é o seu 1º curso de Ciência de Dados? Se sim, escreva s. Para não, n. Resposta: n
Muito prazer,  Kelvin ! Bom contar contigo nesta disciplina :)

## <font color=green size=6>**02. PREPARANDO O AMBIENTE DE TRABALHO**</font>

🤓 **Hoje, usaremos uma sequência de comandos que nos permitirá analisar dados com Python.**

* O nosso primeiro passo será fazer o download de uma base de dados sobre casos de dengue no Brasil. O link é o mesmo que está na primeira célula: [Link-Dados-Dengue-Brasil](https://www.kaggle.com/datasets/jimmyyyyyyy/dengue-in-brazil-2012-2021?select=State_Dengue_Model_Data_w_pop.csv). Apesar deste link, utilize a base que está no Moodle.

**Siga os passos a seguir:**

1. Caso esteja no Google Colab, faça upload da base de dados. Na sequência, obtenha o caminho do arquivo. Ao passar o cursor sobre o arquivo, você verá três pontinhos na vertical, logo na direta do arquivo selecionado. Clique neles e, então, você verá a opção de `Copiar caminho`. Veha a imagem abaixo.

![](https://cdn1.gnarususercontent.com.br/1/547588/9fc47f1b-b54c-4b42-a6e3-a14d3d917ccd.png)

2. Se estiver no Jupyter Notebook, salve o arquivo *.csv no local que desejar, na máquina em que estiver trabalhando. Copie o caminho do arquivo. Veja o exemplo abaixo.

![](https://www.wikihow.com/images/thumb/5/51/Find-a-File%27s-Path-on-Windows-Step-5.jpg/v4-728px-Find-a-File%27s-Path-on-Windows-Step-5.jpg.webp)

*Esta imagem de exemplo é de um site que ensina como obter esse caminho.*
*Acesse o link abaixo, caso precise de mais ajuda.*

[Link-WikiHow-Caminho-Arquivo-Windows](https://pt.wikihow.com/Encontrar-o-Caminho-de-um-Arquivo-no-Windows)

## <font color=green size=6>**03. PRÉ-PROCESSAMENTO**</font>

##### **01. Importe a biblioteca Pandas. Ela possui códigos prontos, para que possamos abrir com o Python a base de dados.**

> Padrão dominante para aplicações Python orientadas a dados. Possui duas estruturas de dados: *Series*, que trabalha com informações em 1 Dimensão, e *DataFrame*, que possui 2 Dimensões. Na prática, o DataFrame é uma coleção de objetos Series.

*Neste [vídeo](https://www.youtube.com/watch?v=yCtiqMRt4TQ), vemos uma síntese sobre o que é e qual o grau de importância do Pandas.*

> O `pd` é um apelido curto, para que possamos nos referir a esta biblioteca e usar os seus recursos em nosso código.

In [5]:
#Montando o caminho para o Google Drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
# Importando a biblioteca pandas com o apelido 'pd'
import pandas as pd

##### **02. Obtenha a base de dados.**
> O `r` antes do caminho do arquivo garante que todos os caracteres desse caminho sejam interpretados como texto. Na ausência dele, a barra invertida é interpretada como caractere de escape, cuja ação depende da próxima letra. Por exemplo: `\n` leva o Python a pular uma linha.

In [8]:
dados = pd.read_csv('/content/drive/MyDrive/Ciência da Computação/Data Science - Projeto de Extensão/DS-002 - Gerenciamento de Dados para Análise/Aula 01/dengue05.csv')

##### **03. Verifique o conteúdo da base de dados, para estar seguro de que os dados foram obtidos adequadamente.**
> Podemos ter uma noção do conteúdo do banco, pedindo para o Python nos mostrar os seus 5 primeiros registros por meio do atributo `.head()`.

In [10]:
# Exibindo as primeiras linhas do dataframe para verificar se o arquivo foi carregado corretamente
dados.head()

,Year,State,Mean_Tmp,Min_Tmp,Max_Tmp,Percipitation,Change_Tmp,State_ID,Cases,Region,State_Area(km2),Population
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687

> Podemos ter uma ideia dos últimos 5 itens do nosso banco, pedindo isso ao Python com o seguinte comando.

In [11]:
# Exibindo as últimas 5 linhas do dataframe
dados.tail()

,Year,State,Mean_Tmp,Min_Tmp,Max_Tmp,Percipitation,Change_Tmp,State_ID,Cases,Region,State_Area(km2),Population
255,2018,Tocantins,27.53,21.81,33.29,1749.54,11.48,17.0,8236,N,277721.0,1555229
256,2019,Tocantins,27.92,21.93,33.96,1271.12,12.03,17.0,30901,N,277721.0,1572866
257,2020,Tocantins,27.74,21.89,33.65,1729.92,11.76,17.0,5625,N,277721.0,1590248
258,2021,Tocantins,27.33,21.62,33.09,1717.39,11.47,17.0,1,N,277721.0,1607363
259,2021,NaN,27.33,21.62,33.09,1717.39,11.47,NaN,1,N,277721.0,1607363

**Informações importantes sobre a base de dados:**

🤔**O que signica cada coluna:**

- Year: ano entre 2012 e 2021
- State: estado brasileiro
- Mean_Tmp: temperatura média em graus Celsius no ano
- Min_Tmp: temperatura mínima em graus Celsius no ano
- Max_Tmp: temperatura máxima em graus Celsius no ano
- Percipitation: precipitação anual em milímetros
- Change_Tmp: temp. máx. anual menos temp. mín. anual em graus Celsius
- State_ID: número de identificação do estado brasileiro
- Cases: número de casos de dengue
- Region: região brasileira (Norte = N, Nordeste = NE, Centro-Oeste = CO, Sudeste = SE, Sul = S)
- State_Area(km2): área em km2 do estado
- Population: estimativa da população total

💻**Como o Pandas guarda os nossos dados:**

- O pandas armazena o nosso banco como um `DataFrame`, que é uma estrutura bi-dimensional, que pode contar diversos tipos de dados, sendo os elementos rotulados.
- Os rótulos das linhas estão no atributo *index*, que são os números de 0 em diante que podem ser vistos acima, na extrema esquerda da tabela. Já os rótulos de colunas ficam no atributo *columns*.
- Daqui em diante, vamos usar o termo `DataFrame` como substiuto de banco de dados.

##### **04. Crie uma cópia do DataFrame original.**
> Esta é uma boa prática, para evitarmos o risco de perder ou modificar algo da base original. Nessa cópia, é útil deixar apenas as variáveis que iremos analisar.

In [12]:
# Criando uma cópia do dataframe original
dados_copia = dados.copy()

##### **05. Consulte o banco copiado, para verificar se está correto.**

In [13]:
# Exibindo as primeiras linhas do dataframe copiado para verificar se está correto
dados_copia.head()

,Year,State,Mean_Tmp,Min_Tmp,Max_Tmp,Percipitation,Change_Tmp,State_ID,Cases,Region,State_Area(km2),Population
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687

##### **06. Verifique quais são os estados que estão presentes no banco de dados.**

In [14]:
# Listando os estados presentes no banco de dados
estados = dados_copia['State'].unique()
print(estados)

['Acre' 'Alagoas' 'Amapa' 'Amazonas' 'Bahia' 'Ceara' 'Distrito Federal'
 'Espirito Santo' 'Goias' 'Maranhao' 'Mato Grosso' 'Mato Grosso Do Sul'
 'Minas Gerais' 'Para' 'Paraiba' nan 'Parana' 'Pernambuco' 'Piaui'
 'Rio De Janeiro' 'Rio Grande Do Norte' 'Rio Grande Do Sul' 'Rondonia'
 'Roraima' 'Santa Catarina' 'Sao Paulo' 'Sergipe' 'Tocantins']

##### **07. Descubra os casos de NaN e NULL na base de dados.**

> Podem ocorrer casos de valores que não são números e de valores nulos. A depender de casa situação, pode ser necessário remover ambos. É o que faremos aqui.

In [15]:
# Casos de valores ausentes

# Verificando a quantidade de valores faltantes em cada coluna
valores_ausentes = dados_copia.isnull().sum()
print(valores_ausentes)

Year               0
State              2
Mean_Tmp           0
Min_Tmp            0
Max_Tmp            0
Percipitation      0
Change_Tmp         0
State_ID           2
Cases              0
Region             0
State_Area(km2)    0
Population         0
dtype: int64

In [16]:
# Casos de valores ausentes
# Exibição das linhas

# Exibição das linhas com valores faltantes
linhas_com_ausentes = dados_copia[dados_copia.isnull().any(axis=1)]
print(linhas_com_ausentes)

     Year State  Mean_Tmp  Min_Tmp  Max_Tmp  Percipitation  Change_Tmp  \
141  2021   NaN     27.33    21.62    33.09        1717.39       11.47
259  2021   NaN     27.33    21.62    33.09        1717.39       11.47

     State_ID  Cases Region  State_Area(km2)  Population
141       NaN      1      N         277721.0     1607363
259       NaN      1      N         277721.0     1607363

In [17]:
# Casos de valores que não são números

# Verificando se há valores que não são números nas colunas numéricas
colunas_numericas = dados_copia.select_dtypes(include=['number']).columns
valores_nao_numericos = dados_copia[colunas_numericas].applymap(lambda x: isinstance(x, (int, float))).all()
print(valores_nao_numericos)

Year               True
Mean_Tmp           True
Min_Tmp            True
Max_Tmp            True
Percipitation      True
Change_Tmp         True
State_ID           True
Cases              True
State_Area(km2)    True
Population         True
dtype: bool

In [18]:
# Casos de valores que não são números

# Exibição das linhas com valores que não são números nas colunas numéricas
linhas_com_nao_numericos = dados_copia[~dados_copia[colunas_numericas].applymap(lambda x: isinstance(x, (int, float))).all(axis=1)]
print(linhas_com_nao_numericos)

Empty DataFrame
Columns: [Year, State, Mean_Tmp, Min_Tmp, Max_Tmp, Percipitation, Change_Tmp, State_ID, Cases, Region, State_Area(km2), Population]
Index: []

##### **08. Remova todos os casos de NaN do banco de dados.**

In [19]:
# Removendo linhas com valores faltantes
dados_clean = dados_copia.dropna()

##### **09. Verifique se ainda existem casos de NaN e avalie como ficou a base de dados.**

In [20]:
# Verificando a quantidade de valores faltantes após a remoção
dados_clean.isnull().sum()

Year               0
State              0
Mean_Tmp           0
Min_Tmp            0
Max_Tmp            0
Percipitation      0
Change_Tmp         0
State_ID           0
Cases              0
Region             0
State_Area(km2)    0
Population         0
dtype: int64

💰**Bônus:**
> Se você quisesse, poderia mudar os nomes das colunas do seu DataFrame. Para isso, basta usar o método `.rename()`.

In [21]:
# Renomeando as colunas do dataframe para português
dados_clean = dados_clean.rename(columns={
    'Year': 'Ano',
    'State': 'Estado',
    'Mean_Tmp': 'Temp_Media',
    'Min_Tmp': 'Temp_Minima',
    'Max_Tmp': 'Temp_Maxima',
    'Percipitation': 'Precipitacao',
    'Change_Tmp': 'Temp_Variacao',
    'State_ID': 'ID_Estado',
    'Cases': 'Casos',
    'Region': 'Regiao',
    'State_Area(km2)': 'Area_Estado_km2',
    'Population': 'Populacao'
})

In [24]:
# Renomeando as colunas do dataframe para português
dados_copia = dados_copia.rename(columns={
    'Year': 'Ano',
    'State': 'Estado',
    'Mean_Tmp': 'Temp_Media',
    'Min_Tmp': 'Temp_Minima',
    'Max_Tmp': 'Temp_Maxima',
    'Percipitation': 'Precipitacao',
    'Change_Tmp': 'Temp_Variacao',
    'State_ID': 'ID_Estado',
    'Cases': 'Casos',
    'Region': 'Regiao',
    'State_Area(km2)': 'Area_Estado_km2',
    'Population': 'Populacao'
})

In [25]:
# Exibindo as primeiras linhas do dataframe copiado para verificar se está correto
dados_clean.head()

,Ano,Estado,Temp_Media,Temp_Minima,Temp_Maxima,Precipitacao,Temp_Variacao,ID_Estado,Casos,Regiao,Area_Estado_km2,Populacao
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687

In [26]:
# Exibindo as primeiras linhas do dataframe copiado para verificar se está correto
dados_copia.head()

,Ano,Estado,Temp_Media,Temp_Minima,Temp_Maxima,Precipitacao,Temp_Variacao,ID_Estado,Casos,Regiao,Area_Estado_km2,Populacao
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687

##### **10. Inspecione algumas características do seu DataFrame.**

In [27]:
# Exibindo informações gerais sobre o dataframe limpo
dados_clean.info()

# Exibindo estatísticas descritivas dos dados numéricos
dados_clean.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, 0 to 258
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ano              258 non-null    int64
 1   Estado           258 non-null    object
 2   Temp_Media       258 non-null    float64
 3   Temp_Minima      258 non-null    float64
 4   Temp_Maxima      258 non-null    float64
 5   Precipitacao     258 non-null    float64
 6   Temp_Variacao    258 non-null    float64
 7   ID_Estado        258 non-null    float64
 8   Casos            258 non-null    int64
 9   Regiao           258 non-null    object
 10  Area_Estado_km2  258 non-null    float64
 11  Populacao        258 non-null    int64
dtypes: float64(7), int64(3), object(2)
memory usage: 26.2+ KB

,Ano,Temp_Media,Temp_Minima,Temp_Maxima,Precipitacao,Temp_Variacao,ID_Estado,Casos,Area_Estado_km2,Populacao
count,258.000000,258.000000,258.000000,258.000000,258.000000,258.000000,258.000000,2.580000e+02,2.580000e+02,2.580000e+02
mean,2016.430233,24.981279,19.670000,30.342519,1375.873953,10.672519,29.275194,4.808953e+04,3.184248e+05,7.726080e+06
std,2.777932,2.460819,2.569256,2.444746,588.433824,0.968027,12.906648,1.169770e+05,3.708127e+05,9.051169e+06
min,2012.000000,17.620000,12.270000,23.030000,328.230000,8.320000,11.000000,1.000000e+00,5.780000e+03,4.695240e+05
25%,2014.000000,23.347500,17.755000,28.952500,862.505000,10.132500,17.000000,2.510250e+03,5.646800e+04,2.781680e+06
50%,2016.000000,25.610000,20.200000,31.015000,1374.880000,10.725000,27.000000,1.137000e+04,2.243010e+05,3.997956e+06
75%,2019.000000,26.907500,21.850000,32.142500,1817.225000,11.280000,41.000000,3.644525e+04,3.401100e+05,9.328312e+06
max,2021.000000,28.000000,22.910000,33.960000,2750.900000,13.120000,53.000000,1.033012e+06,1.559148e+06,4.664913e+07

##### **11. Verifique o tamanho do seu DataFrame.**

In [28]:
# Verificando o tamanho do dataframe
dados_clean.shape

(258, 12)

##### **12. Crie uma nova coluna chamada SeveralCases, que irá conter apenas dois valores: 0, quando o número de casos em uma linha estiver abaixo da mediana do conjunto de dados e 1, quando for maior.**

In [30]:
# Calculando a mediana do número de casos
mediana_casos = dados_clean['Casos'].median()

# Criando a nova coluna 'SeveralCases'
dados_clean['SeveralCases'] = dados_clean['Casos'].apply(lambda x: 1 if x > mediana_casos else 0)

# Exibindo a nova coluna 'SeveralCases'
print(dados_clean['SeveralCases'])

0      0
1      0
2      1
3      1
4      0
      ..
254    1
255    0
256    1
257    0
258    0
Name: SeveralCases, Length: 258, dtype: int64

In [34]:
# Exibindo as primeiras 5 linhas da coluna 'SeveralCases'
print(dados_clean['SeveralCases'].head())

0    0
1    0
2    1
3    1
4    0
Name: SeveralCases, dtype: int64

##### **13. Consulte o DataFrame para examinar se a coluna foi criada.**

In [38]:
# Exibindo as primeiras linhas do dataframe para verificar a nova coluna
dados_clean.head()

,Ano,Estado,Temp_Media,Temp_Minima,Temp_Maxima,Precipitacao,Temp_Variacao,ID_Estado,Casos,Regiao,Area_Estado_km2,Populacao,SeveralCases
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786,0
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463,0
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101,1
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513,1
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687,0

##### **14. Verifique com quantos valores de cada classe (1 e 0) da coluna SeveralCases o seu DataFrame ficou.**

In [40]:
# Contando os valores em cada classe da coluna 'VariosCasos'
dados_clean['SeveralCases'].value_counts()

SeveralCases
0    129
1    129
Name: count, dtype: int64

## <font color=green size=6>**TAREFA 01**</font>
*Esta é a atividade que você fará nas suas horas de aula on-line.*

**1. Usando a base de dados sobre casos de dengue no Brasil, `df_dengue`, renomeie as colunas, com base na dica fornecida acima. Os novos nomes podem ser definidos por você, mas precisam ser em português. Entregue o seu notebook no Moodle, por meio de um link de compartilhamento.**

Vamos começar importando os dados e criando uma cópia do DataFrame original.

In [41]:
import pandas as pd

# Carregar a base de dados original
dados = pd.read_csv('/content/drive/MyDrive/Ciência da Computação/Data Science - Projeto de Extensão/DS-002 - Gerenciamento de Dados para Análise/Aula 01/dengue05.csv')

# Criar uma cópia do DataFrame original
df_dengue = dados.copy()

Aqui, df_dengue será uma cópia exata do DataFrame dados.

In [42]:
# Renomear as colunas do DataFrame df_dengue
df_dengue.rename(columns={
    'Year': 'Ano',
    'State': 'Estado',
    'Population': 'População',
    'Region': 'Região',
    'Min_Tmp': 'Temp_Minima',
    'Max_Tmp': 'Temp_Maxima',
    'Change_Tmp': 'Variacao_Temp',
    'Mean_Tmp': 'Temp_Media',
    'Percipitation': 'Precipitacao',
    'Cases': 'Casos'
}, inplace=True)

In [47]:
# Exibir as primeiras linhas do DataFrame df_dengue
df_dengue.head()

,Ano,Estado,Temp_Media,Temp_Minima,Temp_Maxima,Precipitacao,Variacao_Temp,State_ID,Casos,Região,State_Area(km2),População
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687

In [49]:
# Verificar informações do DataFrame
df_dengue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ano              260 non-null    int64
 1   Estado           258 non-null    object
 2   Temp_Media       260 non-null    float64
 3   Temp_Minima      260 non-null    float64
 4   Temp_Maxima      260 non-null    float64
 5   Precipitacao     260 non-null    float64
 6   Variacao_Temp    260 non-null    float64
 7   State_ID         258 non-null    float64
 8   Casos            260 non-null    int64
 9   Região           260 non-null    object
 10  State_Area(km2)  260 non-null    float64
 11  População        260 non-null    int64
dtypes: float64(7), int64(3), object(2)
memory usage: 24.5+ KB

In [50]:
# Remover linhas com valores ausentes, se necessário
df_dengue.dropna(inplace=True)

# Calcular a mediana dos casos de dengue
mediana_casos = df_dengue['Casos'].median()

# Definir função para identificar se há muitos casos
def ident_se_muitos_casos(casos):
    if casos > mediana_casos:
        return 1
    else:
        return 0

# Criar a coluna 'SeveralCases' com base na função definida
df_dengue['SeveralCases'] = df_dengue['Casos'].apply(ident_se_muitos_casos)

In [51]:
# Exibir a nova coluna 'SeveralCases'
print("\nNova coluna 'SeveralCases':")
print(df_dengue['SeveralCases'])

Nova coluna 'SeveralCases':
0      0
1      0
2      1
3      1
4      0
      ..
254    1
255    0
256    1
257    0
258    0
Name: SeveralCases, Length: 258, dtype: int64

In [52]:
# Exibindo as primeiras linhas do dataframe para verificar a nova coluna
df_dengue.head()

,Ano,Estado,Temp_Media,Temp_Minima,Temp_Maxima,Precipitacao,Variacao_Temp,State_ID,Casos,Região,State_Area(km2),População,SeveralCases
0,2012,Acre,25.74,20.48,31.05,1851.90,10.57,12.0,22,N,164124.0,758786,0
1,2013,Acre,25.61,20.40,30.86,1909.14,10.46,12.0,9229,N,164124.0,776463,0
2,2014,Acre,25.78,20.57,31.04,2243.00,10.47,12.0,36795,N,164124.0,790101,1
3,2015,Acre,26.22,20.88,31.62,1895.83,10.74,12.0,14320,N,164124.0,803513,1
4,2016,Acre,26.16,20.66,31.71,1874.84,11.05,12.0,9237,N,164124.0,816687,0